# Set the base image to Node.js 16 on Alpine Linux
FROM node:16-alpine

# Create a directory named '/app' and change ownership to the 'node' user
RUN mkdir /app && chown node:node /app

# Set the working directory to '/app'
WORKDIR /app

# Set the user to 'node' for subsequent instructions
USER node

# Copy package.json and package-lock.json* from the host to the container '/app' directory
COPY --chown=node:node ./package.json package-lock.json* ./

# Install Node.js dependencies specified in package.json
RUN npm install

# Copy the remaining application files from the host to the container '/app' directory
COPY --chown=node:node . .

# Specify the default command to run when the container starts
CMD ["npm", "run", "start"conf]
