sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm test 

after_sucess:
  - docker build -t  199012118961/multi-client ./client
  - docker build -t  199012118961/multi-nginx ./nginx
  - docker build -t  199012118961/multi-server ./server
  - docker build -t  199012118961/multi-worker ./worker

# docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# push images to the dockerhub
  - docker push  199012118961/multi-client
  - docker push  199012118961/multi-nginx
  - docker push  199012118961/multi-server
  - docker push  199012118961/multi-worker

